SPOI-5739 #resolve Must catch NoClassDefFoundError when processing operator classes in jar, previously catching Throwable was changed to catching Exception